# anki_space_settings.py

from PyQt5.QtWidgets import QMainWindow
from anki_space_settings_ui import Ui_MainWindow  # Ensure this is generated by pyuic5 for PyQt5

class AnkiSpaceSettingsWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        #self.setWindowTitle("Anki Separation Space Configuration")  # Optional, sets window title

        # Connect Cancel button to close the window
        self.ui.btnCancel.clicked.connect(self.close)

        # Connect Save button to a function
        self.ui.btnSave.clicked.connect(self.save_settings)

    def save_settings(self):
        separator = self.ui.lineEdit.text()
        print(f"Saving separator: {separator}")
        self.close()  # Optional: close the window after saving
