# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiprogram.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(280, -50, 981, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 200, 141, 39))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(200, 150, 271, 17))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 80, 261, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.btnMenuExtract = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenuExtract.setGeometry(QtCore.QRect(10, 20, 251, 39))
        self.btnMenuExtract.setObjectName("btnMenuExtract")
        self.btnMenuGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenuGenerate.setGeometry(QtCore.QRect(10, 70, 251, 39))
        self.btnMenuGenerate.setObjectName("btnMenuGenerate")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1140, 480, 93, 39))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 29))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfigure_Anki_Separation_Space = QtWidgets.QAction(MainWindow)
        self.actionConfigure_Anki_Separation_Space.setObjectName("actionConfigure_Anki_Separation_Space")
        self.actionConfigure_HTML_Template = QtWidgets.QAction(MainWindow)
        self.actionConfigure_HTML_Template.setObjectName("actionConfigure_HTML_Template")
        self.actionHow_to_Use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_Use.setObjectName("actionHow_to_Use")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionConfigure_Anki_Separation_Space)
        self.menuSettings.addAction(self.actionConfigure_HTML_Template)
        self.menuAbout.addAction(self.actionHow_to_Use)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "matsuba"))
        self.pushButton_3.setText(_translate("MainWindow", "Select File ..."))
        self.label.setText(_translate("MainWindow", "Add selected notes (TXT format) from Anki."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.btnMenuExtract.setText(_translate("MainWindow", "Extract Japanase Sentence From Anki"))
        self.btnMenuGenerate.setText(_translate("MainWindow", "Generate static HTML pages"))
        self.pushButton_4.setText(_translate("MainWindow", "Extract"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionConfigure_Anki_Separation_Space.setText(_translate("MainWindow", "Configure Anki Separation Space"))
        self.actionConfigure_HTML_Template.setText(_translate("MainWindow", "Configure HTML Template"))
        self.actionHow_to_Use.setText(_translate("MainWindow", "How to Use?"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
